@startuml

' 9
class "Administrador de conodminio" {
  {field} CI
  {field} Nombre
  {field} Apellido
  {field} Telefono
  {field} Direccion
  {field} Fecha de Nacimiento
}

' 2
class Condominio {
  {field} Nombre del Condominio
  {field} Ubicacion
  {field} Cantidad de Casas (o departamentos)
  {field} Tamano
}

' 3
class Proveedor {
  {field} CI
  {field} NIT
  {field} Nombre
  {field} Apellido
  {field} Telefono
  {field} Direccion
}

' 4
class "Empresa Proveedora" {
  {field} NIT
  {field} Correo empresarial
  {field} Nombre de la empresa
  {field} Direccion
  {field} Telefono
  {field} Comentarios
  {field} Calificacion
}

' 10
class "Habitante y CoHabitante" {
  {field} CI (habitante)
  {field} Nombre (habitante)
  {field} Apellido (habitante)
  {field} Telefono (habitante)
}

' 5
class "Tarifario de Membersia Condominio" {
  {field} Nombre del Administrador del Condominio
  {field} Correo del Administrador del Condominio
  {field} NIT del Administrador del Condominio
  {field} Monto de la membresía a pagar 
  {field} Fecha de Inicio
  {field} Fecha de Fin
}

' 6
class "Tarifario de Membersia Proveedor" {
  {field} Nombre del proveedor
  {field} Correo del Proveedor
  {field} NIT del Proveedor
  {field} Monto de la membresía a pagar 
  {field} Fecha de Inicio
  {field} Fecha de Fin
}

' 7
class "Tipo de Pago" {
  Lista de tipos de pago
}

' 11
class "Solicitud Union a Comuniodad Proveedora" {
  {field} Correo del administrador \nde condominio destinatario
  {field} Correo de la empresa proveedora \norigen
  {field} Fecha de solicitud
  {field} Asunto
  {field} Descripción
}

' 12
class "Respuesta de pertenencia \ndel proveedor al condominio" {
  {field} Correo del proveedor destinatario
  {field} Correo del administrador \nde condominio origen
  {field} Fecha y Hora de Respuesta
  {field} Asunto
  {field} Descripción
}

' 13
class "Solicitud de Servicio por Catalogo" {
  {field} Fecha a llevarse a cabo
}
' 14
class "Respuesta Solicitud de Servicio por Catalogo" {
  {field} Fecha de respuesta
}

' 15
class "Solicitud de servicio personalizado" {
  {field} Nombre 
  {field} Descripcion
  {field} Fecha de solicitud
  {field} Fecha de inicio
  {field} Hora de Inicio
  {field} Fotos
}
' 16
class "Respuesta de servicio personalizado" {
  {field} Fecha de respuesta
  {field} Precio
}

' 20
class "Catalogo de servicios" {
  {field} Nombre 
  {field} Descripcion
  {field} Precio
  {field} Fotos
}

' E21
class "Comunidad de proveedores" {
  {field} Lista de Proveedores
}

' E23
class Producto {
  {field} Codigo de Barras 
  {field} Nombre 
  {field} Descripcion 
  {field} Precio
  {field} Stock 
  {field} Comentarios 
  {field} Fotos
  {field} Tiempo de entrega
  {field} Caracteristicas Adicionales
}

' E24
class "Lista de Producto" {
  {field} Fecha de Compra
  {field} Cantidad
  {field} Total
  {field} Tipo de Pago
}

' E25
class "Tarjeta de Credito" {
  {field} Nombre del titular
  {field} Numero de la tarjeta
  {field} Fecha de Expiracion
  {field} Codigo de seguridad (CVV/CVC/CID)
}

' E26
class QR {
  {field} Codigo QR
  {field} Fecha de Expiracion
}

' E27
class "Categoria de Servicios" {
  {field} Nombre
  {field} Descripcion
}

' E28
class "Categoria de Productos" {
  {field} Nombre
  {field} Descripcion
}


class TipoDeCatalogo {
  {field} Nombre
  {field} Descripcion
}

' RELACIONES

' FLUJO CONDOMINIO
Condominio ||--o| "Administrador de conodminio" : "Administra" <
Condominio ||--|| "Comunidad de proveedores" : "vincualdo a una" >

' FLUJO DE SERVICIO PERSONALIZADO
"Habitante y CoHabitante" ||--o{ "Solicitud de servicio personalizado" : "Solicita" >
"Solicitud de servicio personalizado" }o--|| "Comunidad de proveedores" : "Oferta" >
"Respuesta de servicio personalizado" -- "Habitante y CoHabitante"
"Comunidad de proveedores" ||--o{ "Respuesta de servicio personalizado" : Responde >
Proveedor ||--|{ "Categoria de Servicios" : "quiere ver" >


' FLUJO DE SOLICITUD DE PRODUCTO
Proveedor ||--o{ Producto : Tiene >
Producto ||--o{ "Categoria de Productos" : "es de tipo" >
' Producto }o--|| "Comunidad de proveedores" : Oferta >
Producto ||---|{ "Lista de Producto" : "Toma" <
"Lista de Producto" |o--|| "Habitante y CoHabitante" : "crea" <

' FLUJO DE SOLICITUD DE SERVICIO POR CATALOGO
Proveedor ||--o{ "Catalogo de servicios" : "crea" <
"Habitante y CoHabitante" ||--o{ "Solicitud de Servicio por Catalogo" : "Solicita" >
"Solicitud de Servicio por Catalogo" }o--|| "Catalogo de servicios" : "Oferta" >
"Catalogo de servicios" ||--o{ "Respuesta Solicitud de Servicio por Catalogo" : "Responde" >
"Respuesta Solicitud de Servicio por Catalogo" }o--|| "Habitante y CoHabitante" : Acepta <
TipoDeCatalogo ||--|| "Catalogo de servicios" : "es de tipo" >

' FLUJO DE SOLICITUD DE PERTENENCIA (PROVEEDORES|CONMINIO)
' "Administrador de conodminio"
Proveedor }|--o| "Empresa Proveedora" : "pertenece" > 
Proveedor }|--|| "Solicitud Union a Comuniodad Proveedora" : "Solicita" >
"Solicitud Union a Comuniodad Proveedora" }o--|| "Administrador de conodminio" : "Inspecciona" <
"Administrador de conodminio" ||--o{ "Respuesta de pertenencia \ndel proveedor al condominio" : "Responde" >
"Respuesta de pertenencia \ndel proveedor al condominio" |o--|| "Proveedor" : "Acepta" <
Proveedor }o--o{ "Comunidad de proveedores" : "Pertenece" >

' FLUJO DE TARIFA
"Administrador de conodminio" ||--o{ "Tarifario de Membersia Condominio" : "paga" >
"Tarifario de Membersia Proveedor" ||--o{ "Proveedor" : "paga" >
"Tipo de Pago" }|--|| "Tarifario de Membersia Condominio"
"Tipo de Pago" }|--|| "Tarifario de Membersia Proveedor"
"Tipo de Pago" ||--|| "Tarjeta de Credito"
"Tipo de Pago" ||--|| QR


@enduml

