@startuml

' Relacion entre Roles y Personas
class Persona { 
  {field} CI
  {field} Nombre
  {field} Apellido
  {field} Telefono
  {field} Direccion
  {field} Fecha de Nacimiento
}

class Proveedor {
    NIT
}

class AdministradorDeConodminio {
}

class Habitante {
}

class Condominio {
  {field} Nombre
  {field} Direccion
  {field} Telefono
  {field} Cantidad de Edificios
  {field} Cantidad de Apartamentos
  {field} Cantidad de Estacionamientos
  {field} Tamano
}

class EmpresaProveedora {
  {field} Nombre
  {field} Direccion
  {field} Telefono
  {field} Cantidad de Servicios
}

' Productos y Servicios
class Producto {
  {field} Codigo de Barras 
  {field} Nombre 
  {field} Descripcion
  {field} Stock 
  {field} Precio
}

class DetalleDeProducto {
  {field} Cantidad
  {field} PrecioTotal
}

class CatalogoDeProducto {
  {field} Nombre
  {field} Descripcion
}

class Servicio {
  {field} Nombre
  {field} Descripcion
  {field} Precio
}

class CatalogoDeServicios {
  {field} Nombre
  {field} Descripcion
}

class Evaluacion {
  {field} Calificacion
  {field} Comentario
}

' Membrecia a proveedor
class Membresia { 
  {field} Periodo
  {field} Monto
}

class TipoDeMembresia {
  {field} Nombre
  {field} Descripcion
}

class TipoDePago {
  {field} Nombre
  {field} Descripcion
}

class DetalleDePago {
  {field} MontoTotal
  {field} Fecha
}

class Recibo {
  {field} Numero
  {field} Fecha
  {field} Monto
}

class Factura {
  {field} Numero
  {field} Fecha
  {field} Monto
}

class Nota {
  {field} Numero
  {field} Fecha
  {field} Monto
}

' Relacion entre Roles y Personas
Persona <|-- Proveedor
Persona <|-- AdministradorDeConodminio
Persona <|-- Habitante
Proveedor "0..*" -- "1..1" EmpresaProveedora : trabaja con
AdministradorDeConodminio "0..1" -- "1..1" Condominio : administra
Habitante "0..*" -- "1..1" Condominio : vive en

' Relacion Productos y Servicios
EmpresaProveedora "0..*" -- "1..*" Producto : vende
EmpresaProveedora "0..*" -- "1..*" Servicio : ofrece
Producto "0..1" -- "1..1" CatalogoDeProducto : es de tipo
Servicio "0..1" -- "1..1" CatalogoDeServicios : es de tipo

' Relacion de Pago de Producto
Producto "0..*" -- "1..1" DetalleDeProducto : tiene
Habitante "0..*" -- "0..*" DetalleDeProducto : compra
DetalleDeProducto "0..*" -- "1" DetalleDePago : pagado con


' Pago de membrecia a proveedor y tipo de pag
Proveedor "1" -- "1" Membresia : tiene 
Membresia "1" -- "1" TipoDeMembresia : es_de 
Membresia "1" -- "1" DetalleDePago : detalla 
DetalleDePago "1" -- "1" TipoDePago : metodo_de 

DetalleDePago "1" -- "0..1" Recibo : genera 
DetalleDePago "1" -- "0..1" Factura : genera 
DetalleDePago "1" -- "0..1" Nota : genera 

' Evaluacion de Servicios y Productos
Habitante "0..*" -- "0..*" Evaluacion : realiza
AdministradorDeConodminio "0..*" -- "0..*" Evaluacion : realiza
Evaluacion "0..*" -- "1" Servicio : sobre
Evaluacion "0..*" -- "1" Producto : sobre


@enduml