@startuml

object ":Proveedor" as Proveedor
object ":RespuestasDeServcioPersonalizado\nControlador" as Controlador
object ":RespuestaDeServicioPersonalizado" as Respuesta
object ":PoolDeRespuestasDeServicios\nPersonalizados" as PoolRespuesta
object ":PoolDeServicios\nPersonalizados" as PoolServicio


Proveedor -> Controlador : responderSolicitudPersonalizado(id, price)

Controlador -> Respuesta : crearRespuestaPersonalizado(id, price)

Respuesta -> PoolRespuesta : agregarRespuestaPersonalizado(respuesta)

Respuesta -> PoolServicio : retirarSolicitudPersonalizadoSelccionado(id)

@enduml
