@startuml

title Gestionar y Responder a Solicitudes de Servicio Personalizado

actor Proveedor

participant ":RespuestasDeServcioPersonalizado\nControlador" as Controlador
participant ":RespuestasDeServcioPersonalizado" as Respuesta
collections ":PoolDeRespuestasDeServicios\nPersonalizados" as PoolRespuesta
collections ":PoolDeServicios\nPersonalizados" as PoolServicio


== Crear Respuesta a Solicitud de Servicio Personalizado ==
activate Proveedor
Proveedor -> Controlador : responderSolicitudPersonalizado(id, price)
deactivate Proveedor
activate Controlador
Controlador -> Respuesta : crearRespuestaPersonalizado(id, price)
activate Respuesta
deactivate Controlador
Respuesta -> PoolRespuesta : agregarRespuestaCreada(respuesta)
activate PoolRespuesta
PoolRespuesta --> Proveedor : RespuestaCreada()
deactivate PoolRespuesta
activate PoolServicio
Respuesta -> PoolServicio : retirarSolicitudPersonalizadoSelccionado(id)
deactivate Respuesta
deactivate PoolServicio

@enduml
