@startuml
left to right direction
actor "Proveedor"

rectangle "Gestionar Pool de Servicios Personalizados" {
    usecase "Revisar Solicitudes de \nServicios Personalizados" as cu1
    usecase "Visualizar detalles de \nSolicitud de Servicio Personalizado" as cu2
    usecase "Crear respuesta a Solicitudes de \nServicios Personalizados" as cu3

    usecase "Eliminar respuesta" as cu4
    usecase "Modificar respuesta" as cu5
    usecase "Ver todas sus respuestas" as cu6
}

Proveedor --> cu1
Proveedor --> cu2
Proveedor --> cu3
Proveedor --> cu4
Proveedor --> cu5
Proveedor --> cu6


@enduml
