@startuml

object ":Habitante y Cohabitante" as Habitante
object ":Servicio Personalizado" as Servicio
object ":Categoria de Servicios" as Categoria
object ":Pool de Servicio Personalizado" as Pool

Habitante -- Categoria : obtenerCategoriasDeServicios() >
Habitante -- Categoria : mostrarCategoriaDeServicios() <
Habitante -- Servicio : crearSolicitudDeServicioPersonalizado(ServicioPersonalizado) >
Servicio -- Pool : enviarSolicitudDeServicioPersonalizado(ServicioPersonalizado) > 

@enduml
