@startuml

object ":HabitanteYCohabitante" as Habitante
object ":ServicioPersonalizadoControlador" as Controlador
object ":ServicioPersonalizado" as Servicio
object ":CategoriaDeServicios" as Categoria
object ":PoolDeServicioPersonalizado" as Pool

note top of Pool

Pool es una lista de Servicio Personalizado

end note


Habitante -> Controlador : 1. solicitarServicioPersonalizado(ServicioPersonalizado)
Controlador -> Categoria : 2. obtenerCategoriaDeServicio(ServicioPersonalizado.idCategoria)
Controlador -> Servicio : 3. realizarSolicitudDeServicioPersonalizado(ServicioPersonalizado)
Servicio -> Pool : 4. crearSolicitudDeServicioPersonalizado(ServicioPersonalizado)

@enduml
