@startuml

title Gestionar Solicitud de Servicio Personalizado

actor "Habitante y Cohabitante" as Habitante

participant ":ServicioPersonalizado\nContronlador" as Controlador
participant ":CategoriaDeServicios" as Categoria
participant ":ServicioPersonalizado" as Servicio
collections ":PoolDeServicio\nPersonalizado" as Pool

' alt Flujos Basicos
' CREAR
    == Crear Solicitud de Servicio Personalizado ==
    activate Habitante
    Habitante -> Controlador : solicitarServicioPersonalizado(ServicioPersonalizado)
    deactivate Habitante
    activate Controlador
    Controlador -> Categoria : obtenerCategoriaDeServicio(ServicioPersonalizado.idCategoria)
    Controlador -> Servicio : realizarSolicitudDeServicioPersonalizado(ServicioPersonalizado)
    deactivate Controlador
    activate Servicio
    Servicio -> Pool : crearSolicitudDeServicioPersonalizado(ServicioPersonalizado)
    deactivate Servicio
    activate Pool
    Pool --> Habitante : confirmarRecepcionDeSolicitudDeServicioPersonalizado()
    deactivate Pool
    ' ' QUERY
    ' == Consultar Solicitud de Servicio Personalizado ==
    ' Habitante -> Servicio : consultarSolicitudesDeServicioPersonalizado()
    ' activate Servicio
    ' Servicio -> Pool : consultarSolicitudesDeServicioPersonalizado()
    ' deactivate Servicio
    ' Pool --> Habitante : mostrarSolicitudesDeServicioPersonalizado()
    ' deactivate Pool

    ' Habitante -> Servicio : consultarSolicitudDeServicioPersonalizado()
    ' activate Servicio
    ' Servicio -> Pool : consultarSolicitudDeServicioPersonalizado()
    ' deactivate Servicio
    ' Pool --> Habitante : mostrarSolicitudDeServicioPersonalizado()
    ' deactivate Pool



    ' ' CAMINOS ALTERNATIVO
    ' == Modificar Solicitud de Servicio Personalizado ==
    ' alt Modificar Servicio Personalizado Solicitado
    '     Habitante -> Categoria : getCategoriaDeServicios()
    '     activate Categoria
    '     Categoria --> Habitante : mostrarCategoriaDeServicios()
    '     deactivate Categoria
    '     activate Habitante
    '     Habitante -> Habitante : SeleccionarCategoriaDeServicio(idCategoria)
    '     deactivate Habitante
    '     Habitante -> Servicio : modificarSolicitudDeServicioPersonalizado()
    '     activate Servicio
    '     Servicio -> Pool : actualizarSolicitudDeServicioPersonalizado()
    '     deactivate Servicio
    '     Pool -> Pool : publicarActualizacionSolicitudDeServicioPersonalizado()
    '     activate Pool
    '     Pool --> Habitante : confirmarRecepcionDeSolicitudDeServicioPersonalizado()
    '     deactivate Pool
    ' end

    ' == Eliminar Solicitud de Servicio Personalizado ==
    ' alt Eliminar Servicio Personalizado Solicitado
    '     Habitante -> Servicio : eliminarSolicitudDeServicioPersonalizado()
    '     activate Servicio
    '     Servicio -> Pool : eliminarSolicitudDeServicioPersonalizado()
    '     deactivate Servicio
    '     Pool -> Pool : publicarEliminacionSolicitudDeServicioPersonalizado()
    '     activate Pool
    '     Pool --> Habitante : confirmarRecepcionDeSolicitudDeServicioPersonalizado()
    '     deactivate Pool
    ' end
' else Descripcion Incompleta
'     Servicio -> Habitante : errorDescripcionIncompleta()
' end


@enduml
